PRODUCT_PROPERTY_OVERRIDES += \
    ro.qc.sdk.sensors.gestures=true \
    ro.qualcomm.sensors.qmd=true \
    ro.qualcomm.sensors.smd=true \
    ro.qualcomm.sensors.cmc=true \
    ro.qualcomm.sensors.vmd=true \
    ro.qualcomm.sensors.gtap=true \
    ro.qualcomm.sensors.pedometer=true \
    ro.qualcomm.sensors.pam=true \
    ro.qualcomm.sensors.scrn_ortn=true \
    ro.qualcomm.sensors.georv=true \
    ro.qualcomm.sensors.game_rv=true \
    ro.qc.sensors.step_detector=true \
    ro.qc.sensors.step_counter=true \
    ro.qc.sensors.max_geomag_rotvec=true \
    debug.qualcomm.sns.hal=w \
    debug.qualcomm.sns.daemon=w \
    debug.qualcomm.sns.libsensor1=w
